### ISSUE TITLE
Support for Butterfly STM32L433 ARM Cortex M4F

### ISSUE THREAD

**Issue by seamaster101** [thomasonw/NMEA2000_mbed#1]
Hi Thomas,
is there a chance that library will work one day on STM32L433 ARM Cortex M4F?
I'm working on a tilt stabilized rate compass that will output yaw, pitch, roll, and ROT simultaneous in 3 different ways: 
1. NMEA2000; 
2. NMEA0183 (RS232);
3. Sine/cosine analog output needed for Comnav 1001 AP and Furuno 1942 ARPA
The sine/cosine analog output made me choose the Butterfly board [https://www.tindie.com/products/TleraCorp/butterfly-stm32l433-development-board/](url), but appears that it was not the best decision as I can't get the N2K stuff to compile. I've been exchanging emails with Timo, but there is not much he can do without the board. I noticed that there is a tread that you were working with Timo and another guy, trying to make the NMEA2000 stuff platform independent. 
Is there a chance that will happen in the next 1-2 months and i can use the Butterfly STM32L433 for my project or should I abondon it and use Teensy with dual DAC? I like the Butterfly STM32L433 as it is more elegant solution with the built-in DACs, but don't know if it will ever work. I'm not good to write code like that, so I'm hoping you guys will get the Butterfly STM32L433 doing one day.
Cheers!
Jordan

**Comment by thomasonw** [comment]
Hello.

A very interesting project the Butterfly!   I am also looking at migrating to the STM32F series of uC's.  Currently focusing on MBED, but do like the simplicity of the Arduino IDE.   To you question, there needs to be two developments put into place in order to enable the NMEA2000 lib on this product:
  1. Low-level CAN driver APIs, accessing the built in hardware
  2. A NMEA2000 bridge between Tim's lib and the low-level CAN driver APIs

The 1st step would be #1, porting in a low-level CAN driver.  Perhaps this is something @kriswiner would be interested in developing for the Butterfly project?  Once that is in place (and it is not a small effort - but not that bad..), the creation of the NMEA2000 bridge is rather simple.
