### ISSUE TITLE
Edit library NMEA2000_CAN.h

### ISSUE THREAD

**Issue by Lynda96** [thomasonw/NMEA2000_mbed#2]
Hi
I am working on communication with anenometer sensor and NucleoBoard H743ZI2 , this communication is with NMEA2000 , I just wanna read the wind data(direction,speed) from the anenometer sensor and i read this data with NucleoBoard , I am coding with mbed studio OS ,so i wanna know if it works when I include only these librairies on main without NMEA2000_CAN.h ?
#include <N2kMsg.h>
#include <NMEA2000.h>
#include <NMEA2000_mbed.h>       
tNMEA2000 &NMEA2000=*(new tNMEA2000_mbed());
tmbedStream serStream;
Thank you

**Comment by thomasonw** [comment]
Hello.

As I noted in the home page, I stopped working on an MBED version, as the underlying libs did not have sufficient features needed --- specifically the ability to define that Tx and Rx orders be retained in a true FIFO.  For each CPU there are indeed ways to force a true FiFo, but for a generic MBED solution I was not thinking that was appropriate -- and the MBED team did not desire to add any extension that would allow a generic approach for configuring for packet order retention.

I was targeting the STM32F0 at that time, the MBED lib as posted here works with that CPU, so I think you will be fine -- but do check into how to reconfigure the low lying CAN subsystem to preserve FiFo -- turns out some N2K depend on packet order being retained for the Fast Packet protocols, even though there is an index -- not all use them!

To use, yes, you are correct.  This is the header I am using in my CAN module.  It is based on the STM Cube libs, but the declaration is the same using these MBED libs:

```

        #include <N2kMsg.h>                                                 // Auto-select does not work for cubeMX, need to bring in includes directly.
        #include <NMEA2000.h>
          //----  CAN / NMEA2000 linkages.
        //      Need to do them manually, as the cubeMX does not have auto integration into Timo lib


        tNMEA2000 &NMEA2000=*(new tNMEA2000_OSE());
        tOSEStream serStream;

        //*****************************************************************************
        tNMEA2000_OSE::tNMEA2000_OSE() : tNMEA2000()
        {
        }


```

Hope this helps, and good luck!

**Comment by Rania2196** [comment]
Thank you for your help ,so in this case we don't need to include NMEA2000_mbed.h?
cause i select a driver without using NMEA2000_CAN.h ,I defined it by my self like this 

#include <N2kMsg.h>
#include <NMEA2000.h>
#include <NMEA2000_mbed.h>
tNMEA2000 &NMEA2000=*(new tNMEA2000_mbed());
tmbedStream serStream; 
for that i include #include <NMEA2000_mbed.h> ,but I don't understand what do you mean by error 
#error   Make sure file: targets/TARGET_STM/can_api.c   has been edited per  https://github.com/ARMmbed/mbed-os/pull/4121 
and my mbed OS doesn't compile this ,can you explain please 
![canopeno](https://user-images.githubusercontent.com/93643631/158407987-fc84098a-3a7c-4b8e-bd7f-ef40e4d22069.PNG)
